name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install  
      
    - name: Create .env file
      run: |
        # Use > for the first line to create/clear the file
        echo "MONGODB_URI='${{ secrets.MONGODB_URI }}'" > .env
        
        # Use >> for every line after to APPEND without deleting
        echo "GEMINI_API_KEY='${{ secrets.GEMINI_API_KEY }}'" >> .env
        echo "CORS_DEV_ORIGIN='${{ secrets.CORS_DEV_ORIGIN }}'" >> .env
        echo "PORT=5000" >> .env

    - name: Build project
      run: npm run build --if-present

    - name: Deploy with PM2
     
      run: |
        cd $GITHUB_WORKSPACE
        # Check if server.js is here (for your peace of mind in logs)
        ls -la server.js
        
        # Now we use server.js instead of index.js
        pm2 restart backend --update-env || pm2 start ./server.js --name "backend"
        pm2 save
