name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    
    runs-on: self-hosted 

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Deploy with PM2
        run: |
          # 1. Check if the app is already in the list
          # 2. If yes, restart it to pick up new code
          # 3. If no, start it fresh
          pm2 restart backend || pm2 start index.js --name "backend"
          
          # 4. Save the list so it survives a server reboot
          pm2 save
